### ISSUE TITLE
Update deadlineTable output to support styling for table header columns.

### ISSUE THREAD

**Issue by cam-vanorman** [ITS-Digital-Technology/pim-fim-adapter#11]
# Reference
https://nupdgrad2024.wpenginepowered.com/programs/ms-statistics/master-of-science-in-statistics/

# Problem
When 1 table header exists, the table row doesn't span the whole table. This is due to no `colspan` being defined for the header.

<img width="350" alt="Screenshot 2024-12-06 at 11 34 21 AM" src="https://github.com/user-attachments/assets/ad183164-33b5-402e-8cec-a8d2e12abb15">

# Solution
When 1 table header exists, the table header should still span the whole column. For formatting, this may require an empty `td` element with a `colspan` equal to `1` in the `tr` element. When no table headers exist, no table header/row will be displayed.

<img width="350" alt="Screenshot 2024-12-06 at 11 35 42 AM" src="https://github.com/user-attachments/assets/74a7030a-0bcc-4ab3-9c49-4864142ee205">
<img width="350" alt="Screenshot 2024-12-06 at 11 35 46 AM" src="https://github.com/user-attachments/assets/7ddb25b4-8383-4e9f-b27a-7908b94eb8d9">

### Current
https://github.com/ITS-Digital-Technology/pim-fim-adapter/blob/f1a14ffcd333be71b9c6a96919921765c7a356a0/src/PIM/Helpers/transformDeadlinesToTable.php#L46-L54

### Future
Add a `colspan` attribute to the code:

```diff
  foreach ($deadline['headers'] as $thead_th) {
-      if (!empty($thead_th)) {
          $td = $dom->createElement('td');
+         $td = $dom->addAttribute('colspan', 1);
          $td = $thead_tr->appendChild($td);
          
          $th = $dom->createTextNode($thead_th);
          $th = $td->appendChild($th);
      }
-  }
```

**Comment by kenwilliams-nu** [comment]
@cam-vanorman I think the change needs to be `$td->setAttribute('colspan', 1);` as `addAttribute` isn't a method of `DOMDocument`, and the setAttribute() method should be called on the $td element, not on $dom. PR incoming.
