### ISSUE TITLE
Add University Model and helper function to get University entry

### ISSUE THREAD

**Issue by cam-vanorman** [ITS-Digital-Technology/pim-fim-adapter#13]
# Request
In Contentful, there's a singleton (one Entry) content type called "University" that holds fields related to the University.

# Tasks
1. Add a new model class called `University` to the PIM Adapter.
2. Add the following fields to the `University` Model in the PIM Adapter.
   - [ ] `name`
   - [ ] `tuitionDisclaimer`
   - [ ] `estimatedTotalTuitionDisclaimer`
   - [ ] `estimatedFeesDisclaimer`
3. In `PIMAdapter` Class, add new property/variable for `$university_content_type` and set value to `'university'` for use as `$this->university_content_type` throughout the Class.
3. Create new helper method called `getUniversity` in `PIMAdapter` Class. Get Content from `university` content type in Contentful using `$this->adapter->getEntriesByContentType( $this->university_content_type);`. Wrap the method's response in a `mapEntriesToModel` to ensure the response is simplified for those pulling data from the University entry record in Contentful.

**Comment by kenwilliams-nu** [comment]
@cam-vanorman Also needed to update `mapEntriesToModel` in  `src/Helpers/mapEntriesToModel.php`  to include case for 'university' content type.
